'use client';

import Link from 'next/link';
import { CalendarDays, ChevronRight, ClipboardCheck, Database, FilePlus2, Users } from 'lucide-react';
import { AdminHeader, EmptyState, Metric } from '@/components/ui';
import { useData } from '@/lib/data';

export function AdminOverview() {
  const { events, members } = useData();
  const pending = events.filter(e => e.reviewStatus === '待審核');
  return <main className="page-enter"><AdminHeader eyebrow="CONTROL ROOM / 00" title="總覽" detail="今天也把每一場賽事，整理得更可靠。" action={<Link href="/admin/events" data-testid="link-overview-manage" className="inline-flex items-center gap-2 rounded-lg bg-[#17364a] px-4 py-2.5 text-sm font-bold text-white">管理賽事 <ChevronRight size={16} /></Link>} /><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="公開賽事" value={events.filter(e => e.reviewStatus === '已發布').length} icon={<CalendarDays />} tone="teal" /><Metric label="待審核" value={pending.length} icon={<ClipboardCheck />} tone="coral" /><Metric label="資料來源" value={3} icon={<Database />} tone="gold" /><Metric label="活躍成員" value={members.filter(m => m.status === '啟用').length} icon={<Users />} tone="slate" /></div><div className="mt-8 grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section className="rounded-2xl border border-[#d9cfc1] bg-[#f8f4ec] p-6"><div className="flex items-center justify-between"><div><p className="font-mono-custom text-[10px] tracking-[.18em] text-[#ed7659]">REVIEW QUEUE</p><h2 className="mt-1 text-lg font-bold text-[#304a55]">審核佇列</h2></div><Link href="/admin/events" data-testid="link-overview-queue" className="text-xs font-bold text-[#087f8c]">查看全部</Link></div>{pending.length ? <div className="mt-5 space-y-2">{pending.map(e => <div key={e.id} data-testid={`row-pending-${e.id}`} className="flex flex-col gap-3 rounded-xl border border-[#e4dacf] p-4 sm:flex-row sm:items-center"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-[#f9e7c3] text-[#9a6917]"><FilePlus2 size={18} /></div><div className="flex-1"><p className="text-sm font-bold text-[#304a55]">{e.name}</p><p className="mt-1 text-xs text-[#8b8277]">{e.submitterName} · {e.createdAt}</p></div><span className="rounded-full bg-[#f9e7c3] px-2 py-1 text-[10px] font-bold text-[#9a6917]">待審核</span></div>)}</div> : <EmptyState title="佇列是空的" detail="目前沒有等待審核的活動。" />}</section><section className="rounded-2xl bg-[#087f8c] p-6 text-[#f8f4ec]"><p className="font-mono-custom text-[10px] tracking-[.18em] text-[#b9e0de]">DATA HEALTH</p><h2 className="mt-1 text-lg font-bold">資料連線狀態</h2><div className="mt-8 flex items-end gap-3"><span className="font-display text-6xl font-bold">98.4</span><span className="mb-2 font-mono-custom text-sm">/ 100</span></div><div className="mt-4 h-2 rounded-full bg-[#3a9aa1]"><div className="h-full w-[98%] rounded-full bg-[#f5ca6e]" /></div><p className="mt-4 text-xs leading-6 text-[#c7e4e1]">最後檢查 2025-09-12 09:42<br />3 個來源均可正常讀取。</p><Link href="/admin/sources" data-testid="link-data-health" className="mt-6 inline-flex items-center gap-1 text-xs font-bold text-white">檢視來源 <ChevronRight size={14} /></Link></section></div></main>;
}
